name: Build Cores via Docker

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Checkout & build the repo in buildroot
      run: |
        docker run \
        -v ${{ github.workspace }}:/root/workspace \
        techdevangelist/miyoomini-buildroot:latest /bin/bash -c \
        "&& apt-get install -y build-essential gettext intltool libsdl2-dev libpcap-dev && cd /root/workspace && git submodule init && git submodule update && patch -p0 <  buildbot-tweaks.patch && cd libretro-super && ./libretro-buildbot-recipe.sh ../cores-onionos && pwd && cd dist/unix && for i in *.so; do cp ../info/\${i%.*}.info .; done && ls -lah ./"

    - name: Upload the build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: OnionOS cores for arm7neonhf
        path: libretro-super/dist/unix/*
        if-no-files-found: error
        retention-days: 90
